### ISSUE TITLE
Import Issue When Installing bidsschematools

### ISSUE THREAD

**Issue by bendhouseart** [bendhouseart/schema-docs#1]
Not finding schema files including version in schema folder, it's probably a symlink or something. Putting this here so that it gets copied over during the cp and commit in the new action in bendhouseart/bids-specification.

```(venv) galassiae@MH02276145MLI schemacode % pip install .
Processing /Users/galassiae/Projects/schema-docs/schemacode
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      /private/var/folders/5t/0cjjt4t10hz5_qk4tts9gkv40000gs/T/pip-build-env-mrijn315/overlay/lib/python3.8/site-packages/setuptools/config/expand.py:144: UserWarning: File '/Users/galassiae/Projects/schema-docs/schemacode/bidsschematools/data/schema/SCHEMA_VERSION' cannot be found
        warnings.warn(f"File {path!r} cannot be found")
      Traceback (most recent call last):
        File "/private/var/folders/5t/0cjjt4t10hz5_qk4tts9gkv40000gs/T/pip-build-env-mrijn315/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 592, in _parse_version
          Version(version)
        File "/private/var/folders/5t/0cjjt4t10hz5_qk4tts9gkv40000gs/T/pip-build-env-mrijn315/overlay/lib/python3.8/site-packages/setuptools/_vendor/packaging/version.py", line 266, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: ''
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/galassiae/Projects/schema-docs/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/galassiae/Projects/schema-docs/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/galassiae/Projects/schema-docs/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/5t/0cjjt4t10hz5_qk4tts9gkv40000gs/T/pip-build-env-mrijn315/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/5t/0cjjt4t10hz5_qk4tts9gkv40000gs/T/pip-build-env-mrijn315/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/5t/0cjjt4t10hz5_qk4tts9gkv40000gs/T/pip-build-env-mrijn315/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/private/var/folders/5t/0cjjt4t10hz5_qk4tts9gkv40000gs/T/pip-build-env-mrijn315/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/5t/0cjjt4t10hz5_qk4tts9gkv40000gs/T/pip-build-env-mrijn315/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/Users/galassiae/Projects/schema-docs/venv/lib/python3.8/site-packages/_virtualenv.py", line 21, in parse_config_files
          result = old_parse_config_files(self, *args, **kwargs)
        File "/private/var/folders/5t/0cjjt4t10hz5_qk4tts9gkv40000gs/T/pip-build-env-mrijn315/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 864, in parse_config_files
          setupcfg.parse_configuration(
        File "/private/var/folders/5t/0cjjt4t10hz5_qk4tts9gkv40000gs/T/pip-build-env-mrijn315/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 174, in parse_configuration
          meta.parse()
        File "/private/var/folders/5t/0cjjt4t10hz5_qk4tts9gkv40000gs/T/pip-build-env-mrijn315/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 496, in parse
          section_parser_method(section_options)
        File "/private/var/folders/5t/0cjjt4t10hz5_qk4tts9gkv40000gs/T/pip-build-env-mrijn315/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 470, in parse_section
          self[name] = value
        File "/private/var/folders/5t/0cjjt4t10hz5_qk4tts9gkv40000gs/T/pip-build-env-mrijn315/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 278, in __setitem__
          value = parser(value)
        File "/private/var/folders/5t/0cjjt4t10hz5_qk4tts9gkv40000gs/T/pip-build-env-mrijn315/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 598, in _parse_version
          raise DistutilsOptionError(tmpl.format(**locals()))
      distutils.errors.DistutilsOptionError: Version loaded from file:bidsschematools/data/schema/SCHEMA_VERSION does not comply with PEP 440:
      [end of output]
```

**Comment by bendhouseart** [comment]
Fixed w/ de-reference of symlinks on main spec [bendhouseart/bids-specification](https://github.com/bendhouseart/bids-specification/commit/68c1849a9d089d271b01acfb71c6b6236fe6ab1a results can be seen here: 6f6f3110
